name: saka
description: Community App.

publish_to: 'none' 

version: 1.9.8+43

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dependency_overrides:
  wakelock_windows: any
  win32: any  

dev_dependencies:
  flutter_test:
    sdk: flutter

   # A
  audio_video_progress_bar: ^0.11.0

  # B
  badges: ^3.0.2
  bubble_tab_indicator: ^0.1.6

  # C
  cupertino_icons: ^1.0.2
  clipboard: ^0.1.3
  chewie: ^1.5.0
  circular_countdown_timer: ^0.2.0
  chips_choice: ^3.0.0
  carousel_slider: ^4.0.0
  currency_text_input_formatter: ^2.1.5
  cached_network_image: ^3.1.0

  # D
  dio: ^4.0.0
  delayed_display: ^2.0.0
  draggable_float_widget: ^0.0.2
  draggable_widget: ^2.0.0
  date_time_picker:
    git:
      url: https://github.com/DavidHDJ/date_time_picker.git
      ref: 2.1.1
  dots_indicator: ^2.0.0

  # E
  expandable: ^5.0.1
  external_path: ^1.0.1

  # Firebase
  firebase_messaging: ^11.2.4
  firebase_core: ^1.10.5
  firebase_core_platform_interface: 4.5.1

  # F
  flutter_pdfview: ^1.2.1
  filesize: ^2.0.1
  flutter_native_contact_picker: ^0.0.4
  flutter_html: ^3.0.0-alpha.6
  floating_bottom_navigation_bar: ^1.5.2
  flutter_rating_bar: ^4.0.0
  flappy_search_bar_ns: ^2.0.2
  fluttertoast: ^8.2.2
  flutter_svg: ^2.0.7
  flutter_animator: ^3.2.2
  flutter_staggered_grid_view: ^0.4.0
  file_picker: ^5.3.2
  flutter_switch: ^0.3.2
  flutter_polyline_points: ^1.0.0
  flutter_animated_dialog: ^2.0.1
  flutter_local_notifications: ^15.1.1
  flutter_link_previewer: ^2.6.1
  flutter_spinkit: ^5.1.0
  flutter_facebook_auth: ^4.1.2
  flutter_launcher_icons: ^0.9.2 

  # G
  gallery_saver: ^2.3.2
  get_it: ^7.1.3
  geolocator: ^9.0.2
  geocoding: ^2.0.4
  google_sign_in: ^5.2.4
  google_maps_flutter: ^2.2.1
  google_maps_place_picker_mb: ^2.0.0-mb.9
 
  # H
  hex: ^0.2.0
  
  # I
  image_cropper: ^1.4.1
  image_gallery_saver: ^2.0.3
  image_picker: ^1.0.4

  # L 
  lecle_flutter_absolute_path: ^0.0.2

  # J 
  jwt_decoder: ^2.0.1
  just_audio: ^0.9.30
  just_audio_background: ^0.0.1-beta.9

  # M
  mask_text_input_formatter: ^2.1.0
  multi_image_picker_plus: ^0.0.3
  mime: ^1.0.1
  modal_bottom_sheet:
    git:
      url: https://github.com/danReynolds/modal_bottom_sheet.git
      path: modal_bottom_sheet

  # N
  new_version_plus: ^0.0.10

  # P
  provider: ^6.0.1
  path_provider: ^2.0.5 
  permission_handler: ^11.0.1
  photo_view: ^0.14.0
  pin_code_fields: ^7.3.0

  # R
  readmore: ^2.1.0
  rxdart: ^0.27.5

  # S
  shimmer: ^2.0.0
  slide_to_confirm: ^1.1.0
  shared_preferences: ^2.0.13
  soundpool: ^2.3.0
  syncfusion_flutter_calendar: ^22.2.10
  sn_progress_dialog: ^1.0.3

  # T
  table_calendar: ^3.0.3
  tap_debouncer: ^2.0.1
  timeago: ^3.4.0
  timelines: ^0.1.0
  timeline_list: ^0.0.6

  # Q
  qr_code_scanner: ^1.0.1

  # U
  url_launcher: ^6.0.20

  # V
  video_player: ^2.3.0
  video_compress: ^3.1.2

  # W
  webview_flutter: ^4.2.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/ic-app.png"

flutter:

  uses-material-design: true

  assets:
  - assets/images/
  - assets/images/logo/
  - assets/images/svg/
  - assets/images/feed/
  - assets/images/background/
  - assets/images/icons/couriers/
  - assets/images/icons/
  - assets/images/update/
  - assets/imagesv2/
  - assets/imagesv2/svg/
  - assets/imagesv2/onboarding/
  - assets/icons/
  - assets/language/
  - assets/pdf/
  - assets/sounds/

  fonts:
    - family: Poppins
      fonts: 
      - asset: assets/fonts/poppins/Poppins-Regular.ttf
      - asset: assets/fonts/poppins/Poppins-Italic.ttf
      - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
    - family: Roboto
      fonts: 
      - asset: assets/fonts/roboto/Roboto-Regular.ttf
      - asset: assets/fonts/roboto/Roboto-Italic.ttf
      - asset: assets/fonts/roboto/Roboto-Bold.ttf