// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3K87Q7ZKA57hLn5o0jhih7KJ_vTlDgeQ',
    appId: '1:94689171996:web:03359e4393901f17ec5dd9',
    messagingSenderId: '94689171996',
    projectId: 'communityapp-67cba',
    authDomain: 'communityapp-67cba.firebaseapp.com',
    storageBucket: 'communityapp-67cba.firebasestorage.app',
    measurementId: 'G-CLM99V4JW9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsovVvo3tMIHcceuoeWz-Zf6i83bNR1GM',
    appId: '1:94689171996:android:7b33653ef3481bfdec5dd9',
    messagingSenderId: '94689171996',
    projectId: 'communityapp-67cba',
    storageBucket: 'communityapp-67cba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARjwS4kbh770FkAMYIt_InM9SuQb-A80E',
    appId: '1:94689171996:ios:d6d1cb85b391d666ec5dd9',
    messagingSenderId: '94689171996',
    projectId: 'communityapp-67cba',
    storageBucket: 'communityapp-67cba.firebasestorage.app',
    iosClientId: '94689171996-lgdrnlu7cv654n83qe5btmd6ul7tm0b6.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileSaka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARjwS4kbh770FkAMYIt_InM9SuQb-A80E',
    appId: '1:94689171996:ios:d6d1cb85b391d666ec5dd9',
    messagingSenderId: '94689171996',
    projectId: 'communityapp-67cba',
    storageBucket: 'communityapp-67cba.firebasestorage.app',
    iosClientId: '94689171996-lgdrnlu7cv654n83qe5btmd6ul7tm0b6.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileSaka',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3K87Q7ZKA57hLn5o0jhih7KJ_vTlDgeQ',
    appId: '1:94689171996:web:00fe15f2dc90096eec5dd9',
    messagingSenderId: '94689171996',
    projectId: 'communityapp-67cba',
    authDomain: 'communityapp-67cba.firebaseapp.com',
    storageBucket: 'communityapp-67cba.firebasestorage.app',
    measurementId: 'G-M9FMFMGVXL',
  );
}
